name: Publish to PyPI

on:
  push:
    branches: [ main ]

jobs:
  build-n-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v2
  
      - name: set up
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' 

      - name: Install build
        run:  pip install build

      - name: Build a binary wheel and a source tarball
        run:  python -m build --sdist --wheel --outdir dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}